# aggregate_weighted_features.py

import numpy as np
import torch
import os
import pandas as pd # Ensure pandas is imported
from tqdm import tqdm # Ensure tqdm is imported

# Define paths to the .pt files generated by extract_dr.py
# These paths are relative to the project root when running with 'python -m'
INPUT_FEATURES_AGO = "data/processed/weighted_esm/per_pair_residue_features_apo_ago.pt"
INPUT_FEATURES_ANT = "data/processed/weighted_esm/per_pair_residue_features_apo_ant.pt"
INPUT_FEATURES_STATE = "data/processed/weighted_esm/per_pair_residue_features_ago_ant.pt"

# Output directory for the final aggregated features
OUTPUT_AGGREGATED_FEATURES_DIR = "data/processed/aggregated_weighted_esm"
os.makedirs(OUTPUT_AGGREGATED_FEATURES_DIR, exist_ok=True)

# Output paths for the final aggregated features
OUTPUT_AGGREGATED_FEATURES_LINEAR = os.path.join(OUTPUT_AGGREGATED_FEATURES_DIR, "aggregated_weighted_features_linear.pt")
OUTPUT_AGGREGATED_FEATURES_SOFTMAX = os.path.join(OUTPUT_AGGREGATED_FEATURES_DIR, "aggregated_weighted_features_softmax.pt")


# --- Weighting Functions ---
def linear_weighting(displacements: np.ndarray) -> np.ndarray:
    """
    Modified to perform simple, unweighted averaging.
    Returns uniform weights, effectively averaging ESM embeddings.
    """
    if displacements.size == 0:
        return np.array([])
    # Return uniform weights for simple averaging
    # Each residue contributes equally regardless of its displacement value
    return np.ones_like(displacements) / len(displacements)



def softmax_weighting(displacements: np.ndarray, temperature: float = 0.0002) -> np.ndarray:
    """
    Applies softmax weighting based on displacement values, scaled by temperature.
    Higher displacement values get exponentially higher weights.
    Temperature controls the 'sharpness' of the distribution.
    A higher temperature (e.g., 2.0) makes the distribution flatter.
    A lower temperature (e.g., 0.5) makes it sharper (more discriminative).
    """
    if displacements.size == 0:
        return np.array([])
        
    scaled_disps = displacements / temperature
    exp_disps = np.exp(scaled_disps - np.max(scaled_disps)) # Subtract max for numerical stability
    
    total_exp = np.sum(exp_disps)
    if total_exp > 0:
        weights = exp_disps / total_exp
    else:
        # Fallback if all exp_disps are zero (e.g., due to extreme negative scaled_disps from low temp)
        weights = np.ones_like(displacements) / len(displacements)
        
    return weights


# --- Helper function for calculating spatial features ---
def calculate_spatial_features(per_residue_data: list, displacements: np.ndarray, weighting_func: callable) -> np.ndarray:
    """
    Calculates the 6D spatial features (weighted centroid, mean/std distances, count)
    for a set of per-residue data.
    
    Args:
        per_residue_data (list): List of dictionaries, each containing 'Coordinate_Apo' or 'Coordinate_Ago'.
        displacements (np.ndarray): 1D array of displacement values for these residues.
        weighting_func (callable): The weighting function (linear_weighting or softmax_weighting) to use for centroid.

    Returns:
        np.ndarray: A 6-dimensional array of spatial features.
    """
    if not per_residue_data:
        return np.zeros(6, dtype=np.float32)

    # Extract coordinates (use Apo/Ago coordinates as the base for spatial features)
    # The dictionary key depends on the comparison type ('Coordinate_Apo' or 'Coordinate_Ago')
    # We prioritize 'Coordinate_Apo' as the common reference, falling back to 'Coordinate_Ago'
    coords = []
    for res_data in per_residue_data:
        if 'Coordinate_Apo' in res_data and res_data['Coordinate_Apo'] is not None:
            coords.append(res_data['Coordinate_Apo'])
        elif 'Coordinate_Ago' in res_data and res_data['Coordinate_Ago'] is not None: # For AgoAnt, use Ago as reference
            coords.append(res_data['Coordinate_Ago'])
    
    coords = np.array(coords, dtype=np.float32)
    
    if coords.size == 0: # If no valid coordinates were extracted
        return np.zeros(6, dtype=np.float32)

    num_residues = len(coords)

    # 1. Weighted Centroid (3D)
    # Apply the same weighting function to displacements for centroid calculation
    weights_for_spatial = weighting_func(displacements)
    
    # Ensure weights match number of coordinates
    if len(weights_for_spatial) != num_residues:
        # Fallback to uniform weights for spatial if mismatch (shouldn't happen with correct data)
        # print(f"[WARNING] Mismatch in weights and coordinates for spatial features. Falling back to uniform weights for centroid.")
        weights_for_spatial = np.ones(num_residues) / num_residues

    weighted_centroid = np.sum(coords * weights_for_spatial[:, np.newaxis], axis=0).astype(np.float32)

    # 2. Mean and Standard Deviation of Inter-Residue Distances (2D)
    if num_residues <= 1: # Cannot calculate pairwise distances for 0 or 1 residue
        mean_dist = 0.0
        std_dist = 0.0
    else:
        # Calculate all pairwise distances
        pairwise_distances = np.linalg.norm(coords[:, np.newaxis, :] - coords[np.newaxis, :, :], axis=2)
        # Get upper triangle elements (excluding diagonal) to avoid duplicates and self-distances
        upper_triangle_indices = np.triu_indices(num_residues, k=1)
        dist_values = pairwise_distances[upper_triangle_indices]
        
        mean_dist = float(np.mean(dist_values))
        std_dist = float(np.std(dist_values))

    # 3. Count of Common Binding Residues (1D)
    count_residues = float(num_residues)

    # Concatenate all 6 spatial features
    return np.concatenate([
        weighted_centroid,
        np.array([mean_dist, std_dist, count_residues], dtype=np.float32)
    ]).astype(np.float32)


# --- Main Aggregation Logic ---
def aggregate_features():
    """
    Loads per-pair, per-residue features, applies ESM-1b weighting,
    calculates spatial features, and aggregates into final GPCR feature vectors.
    """
    print("[INFO] Loading per-pair, per-residue features...")
    # Load the .pt files generated by extract_dr.py
    # Use map_location='cpu' to load safely if saved from GPU and currently on CPU
    try:
        # Check if files exist before loading
        if not os.path.exists(INPUT_FEATURES_AGO):
            raise FileNotFoundError(f"{INPUT_FEATURES_AGO} not found.")
        if not os.path.exists(INPUT_FEATURES_ANT):
            raise FileNotFoundError(f"{INPUT_FEATURES_ANT} not found.")
        if not os.path.exists(INPUT_FEATURES_STATE):
            raise FileNotFoundError(f"{INPUT_FEATURES_STATE} not found.")

        apo_ago_data = torch.load(INPUT_FEATURES_AGO, map_location='cpu')
        apo_ant_data = torch.load(INPUT_FEATURES_ANT, map_location='cpu')
        ago_ant_data = torch.load(INPUT_FEATURES_STATE, map_location='cpu')
    except FileNotFoundError as e:
        print(f"[ERROR] Required input file not found: {e}. Please ensure extract_dr.py ran successfully and generated these files.")
        return
    except Exception as e:
        print(f"[ERROR] Failed to load input feature files: {e}")
        return

    # Combine all UniProt IDs that have any data across the three comparison types
    all_uids = set(apo_ago_data.keys()) | set(apo_ant_data.keys()) | set(ago_ant_data.keys())
    
    final_features_linear = {}
    final_features_softmax = {}

    print(f"[INFO] Aggregating features for {len(all_uids)} GPCRs...")
    # Use tqdm to show progress for the main aggregation loop
    for uid in tqdm(sorted(list(all_uids)), desc="Aggregating GPCR features"):
        # Lists to hold features for this GPCR from all its valid comparisons
        weighted_esm_vectors_linear_per_gpcr = []
        weighted_esm_vectors_softmax_per_gpcr = []
        spatial_features_per_gpcr = []

        # --- Process Apo-Agonist comparisons for this GPCR ---
        if uid in apo_ago_data:
            for comparison_data in apo_ago_data[uid]:
                per_residue_data = comparison_data['Per_Residue_Data']
                
                # Extract displacements and ESM embeddings for current comparison
                # Ensure data is numpy array for operations
                displacements = np.array([d['Displacement'] for d in per_residue_data if 'Displacement' in d])
                esm_embeddings = np.array([d['ESM1b_Embedding'] for d in per_residue_data if 'ESM1b_Embedding' in d])

                # Skip if no valid per-residue data for weighting
                if displacements.size == 0 or esm_embeddings.size == 0:
                    continue 

                # Apply linear weighting to displacements and compute weighted ESM vector
                weights_linear = linear_weighting(displacements)
                weighted_esm_linear = np.sum(esm_embeddings * weights_linear[:, np.newaxis], axis=0).astype(np.float32)
                weighted_esm_vectors_linear_per_gpcr.append(weighted_esm_linear)

                # Apply softmax weighting to displacements and compute weighted ESM vector
                weights_softmax = softmax_weighting(displacements)
                weighted_esm_softmax = np.sum(esm_embeddings * weights_softmax[:, np.newaxis], axis=0).astype(np.float32)
                weighted_esm_vectors_softmax_per_gpcr.append(weighted_esm_softmax)
                
                # Calculate spatial features for this comparison
                # Using linear weighting for the centroid calculation within calculate_spatial_features
                spatial_feats = calculate_spatial_features(per_residue_data, displacements, linear_weighting) 
                spatial_features_per_gpcr.append(spatial_feats)

        # --- Process Apo-Antagonist comparisons for this GPCR (similar logic) ---
        if uid in apo_ant_data:
            for comparison_data in apo_ant_data[uid]:
                per_residue_data = comparison_data['Per_Residue_Data']
                displacements = np.array([d['Displacement'] for d in per_residue_data if 'Displacement' in d])
                esm_embeddings = np.array([d['ESM1b_Embedding'] for d in per_residue_data if 'ESM1b_Embedding' in d])

                if displacements.size == 0 or esm_embeddings.size == 0:
                    continue

                weights_linear = linear_weighting(displacements)
                weighted_esm_linear = np.sum(esm_embeddings * weights_linear[:, np.newaxis], axis=0).astype(np.float32)
                weighted_esm_vectors_linear_per_gpcr.append(weighted_esm_linear)

                weights_softmax = softmax_weighting(displacements)
                weighted_esm_softmax = np.sum(esm_embeddings * weights_softmax[:, np.newaxis], axis=0).astype(np.float32)
                weighted_esm_vectors_softmax_per_gpcr.append(weighted_esm_softmax)

                spatial_feats = calculate_spatial_features(per_residue_data, displacements, linear_weighting)
                spatial_features_per_gpcr.append(spatial_feats)

        # --- Process Agonist-Antagonist comparisons for this GPCR (similar logic) ---
        if uid in ago_ant_data:
            for comparison_data in ago_ant_data[uid]:
                per_residue_data = comparison_data['Per_Residue_Data']
                displacements = np.array([d['Displacement'] for d in per_residue_data if 'Displacement' in d])
                esm_embeddings = np.array([d['ESM1b_Embedding'] for d in per_residue_data if 'ESM1b_Embedding' in d])

                if displacements.size == 0 or esm_embeddings.size == 0:
                    continue

                weights_linear = linear_weighting(displacements)
                weighted_esm_linear = np.sum(esm_embeddings * weights_linear[:, np.newaxis], axis=0).astype(np.float32)
                weighted_esm_vectors_linear_per_gpcr.append(weighted_esm_linear)

                weights_softmax = softmax_weighting(displacements)
                weighted_esm_softmax = np.sum(esm_embeddings * weights_softmax[:, np.newaxis], axis=0).astype(np.float32)
                weighted_esm_vectors_softmax_per_gpcr.append(weighted_esm_softmax)

                spatial_feats = calculate_spatial_features(per_residue_data, displacements, linear_weighting)
                spatial_features_per_gpcr.append(spatial_feats)


        # --- Final Aggregation Across All Comparison Types for this GPCR ---
        # Calculate the mean of weighted ESM vectors across all valid comparisons for this GPCR
        final_weighted_esm_linear = np.zeros(1280, dtype=np.float32)
        if weighted_esm_vectors_linear_per_gpcr:
            final_weighted_esm_linear = np.mean(np.array(weighted_esm_vectors_linear_per_gpcr), axis=0)

        final_weighted_esm_softmax = np.zeros(1280, dtype=np.float32)
        if weighted_esm_vectors_softmax_per_gpcr:
            final_weighted_esm_softmax = np.mean(np.array(weighted_esm_vectors_softmax_per_gpcr), axis=0)
        
        # Calculate the mean of spatial features across all valid comparisons for this GPCR
        final_spatial_features = np.zeros(6, dtype=np.float32)
        if spatial_features_per_gpcr:
            final_spatial_features = np.mean(np.array(spatial_features_per_gpcr), axis=0)
            
        # Combine weighted ESM and spatial features into the final 1286-dim feature vector
        final_1286_linear = np.concatenate([final_weighted_esm_linear, final_spatial_features]).astype(np.float32)
        final_1286_softmax = np.concatenate([final_weighted_esm_softmax, final_spatial_features]).astype(np.float32)
        
        # Store the final 1286-dim feature vectors for this GPCR
        final_features_linear[uid] = final_1286_linear
        final_features_softmax[uid] = final_1286_softmax

    # Save final aggregated features to .pt files
    torch.save(final_features_linear, OUTPUT_AGGREGATED_FEATURES_LINEAR)
    print(f"[INFO] Final linear-weighted features saved to {OUTPUT_AGGREGATED_FEATURES_LINEAR}")
    
    torch.save(final_features_softmax, OUTPUT_AGGREGATED_FEATURES_SOFTMAX)
    print(f"[INFO] Final softmax-weighted features saved to {OUTPUT_AGGREGATED_FEATURES_SOFTMAX}")


# --- Main execution block for the script ---
if __name__ == "__main__":
    print("--- Starting Feature Aggregation and Weighting ---")
    aggregate_features()
    print("--- Feature Aggregation and Weighting Complete ---")